# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/fernando/Desktop/Dev/cpp/graphics/sfml/proyects/minecraft-mainscreen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/fernando/Desktop/Dev/cpp/graphics/sfml/proyects/minecraft-mainscreen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fernando/Desktop/Dev/cpp/graphics/sfml/proyects/minecraft-mainscreen/CMakeFiles /Users/fernando/Desktop/Dev/cpp/graphics/sfml/proyects/minecraft-mainscreen//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fernando/Desktop/Dev/cpp/graphics/sfml/proyects/minecraft-mainscreen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Minecraft

# Build rule for target.
Minecraft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Minecraft
.PHONY : Minecraft

# fast build rule for target.
Minecraft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/build
.PHONY : Minecraft/fast

src/Engine/Engine.o: src/Engine/Engine.cpp.o
.PHONY : src/Engine/Engine.o

# target to build an object file
src/Engine/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Engine/Engine.cpp.o
.PHONY : src/Engine/Engine.cpp.o

src/Engine/Engine.i: src/Engine/Engine.cpp.i
.PHONY : src/Engine/Engine.i

# target to preprocess a source file
src/Engine/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Engine/Engine.cpp.i
.PHONY : src/Engine/Engine.cpp.i

src/Engine/Engine.s: src/Engine/Engine.cpp.s
.PHONY : src/Engine/Engine.s

# target to generate assembly for a file
src/Engine/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Engine/Engine.cpp.s
.PHONY : src/Engine/Engine.cpp.s

src/Screens/TittleScreen/MainScreen.o: src/Screens/TittleScreen/MainScreen.cpp.o
.PHONY : src/Screens/TittleScreen/MainScreen.o

# target to build an object file
src/Screens/TittleScreen/MainScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Screens/TittleScreen/MainScreen.cpp.o
.PHONY : src/Screens/TittleScreen/MainScreen.cpp.o

src/Screens/TittleScreen/MainScreen.i: src/Screens/TittleScreen/MainScreen.cpp.i
.PHONY : src/Screens/TittleScreen/MainScreen.i

# target to preprocess a source file
src/Screens/TittleScreen/MainScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Screens/TittleScreen/MainScreen.cpp.i
.PHONY : src/Screens/TittleScreen/MainScreen.cpp.i

src/Screens/TittleScreen/MainScreen.s: src/Screens/TittleScreen/MainScreen.cpp.s
.PHONY : src/Screens/TittleScreen/MainScreen.s

# target to generate assembly for a file
src/Screens/TittleScreen/MainScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Screens/TittleScreen/MainScreen.cpp.s
.PHONY : src/Screens/TittleScreen/MainScreen.cpp.s

src/Utils/ResourceRandomizer/ResourceRandomizer.o: src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.o
.PHONY : src/Utils/ResourceRandomizer/ResourceRandomizer.o

# target to build an object file
src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.o
.PHONY : src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.o

src/Utils/ResourceRandomizer/ResourceRandomizer.i: src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.i
.PHONY : src/Utils/ResourceRandomizer/ResourceRandomizer.i

# target to preprocess a source file
src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.i
.PHONY : src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.i

src/Utils/ResourceRandomizer/ResourceRandomizer.s: src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.s
.PHONY : src/Utils/ResourceRandomizer/ResourceRandomizer.s

# target to generate assembly for a file
src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.s
.PHONY : src/Utils/ResourceRandomizer/ResourceRandomizer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Minecraft"
	@echo "... src/Engine/Engine.o"
	@echo "... src/Engine/Engine.i"
	@echo "... src/Engine/Engine.s"
	@echo "... src/Screens/TittleScreen/MainScreen.o"
	@echo "... src/Screens/TittleScreen/MainScreen.i"
	@echo "... src/Screens/TittleScreen/MainScreen.s"
	@echo "... src/Utils/ResourceRandomizer/ResourceRandomizer.o"
	@echo "... src/Utils/ResourceRandomizer/ResourceRandomizer.i"
	@echo "... src/Utils/ResourceRandomizer/ResourceRandomizer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

